### ISSUE TITLE
whitespace problem

### ISSUE THREAD

**Issue by l4t3b0** [pfidr34/docker-rclone#13]
Hi pfidr34

I really like your rclone distribution. i use it with unraid and works well until now 👍 

i set up several docker instances and now i had to face a problem where the SYNC_SRC includes whitespaces.

Here is my docker command:
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='rclone-alapitvany-private' --net='bridge' -e TZ="Europe/Budapest" -e HOST_OS="Unraid" -e 'SYNC_SRC'='webdav-alapitvany-private:/Megosztott dokumentumok/' -e 'SYNC_OPTS'='-v' -e 'SYNC_ONCE'='' -e 'CRON'='@weekly' -e 'CRON_ABORT'='' -e 'FORCE_SYNC'='1' -e 'RCLONE_CMD'='copy' -e 'RCLONE_DIR_CMD'='ls' -e 'RCLONE_DIR_CHECK_SKIP'='' -e 'CHECK_URL'='https://hc-ping.com/d34f5..........023cd' -e 'OUTPUT_LOG'='' -e 'ROTATE_LOG'='120' -e 'SYNC_DEST'='/data' -v '/mnt/user/Cloud Backup/webdav-alapitvany-private/':'/data':'rw' -v '/mnt/user/appdata/rclone':'/config':'rw' 'pfidr/rclone'

And the corresponding log when i start the container:
INFO: Running rclone v1.51.0
INFO: Cron shortcut @weekly re-written to 0 0 * * 0
INFO: Starting sync.sh pid 31 Sun May 10 20:27:13 CEST 2020
INFO: Removing logs older than 120 day(s)...
Usage:
rclone ls remote:path [flags]

Flags:
-h, --help help for ls

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.
Command ls needs 1 arguments maximum: you provided 2 non flag arguments: ["webdav-alapitvany-private:/Megosztott" "dokumentumok/"]
WARNING: Source directory is empty. Skipping copy command.
INFO: Add CRON_ABORT="0 6 * * *" to cancel outstanding sync at 6am
INFO: Starting crond ...
INFO: crond started
==> /tmp/crond.log <==

==> /tmp/sync.log <==

Please confirm, that it is not a configuration issue on my side and let me know what could be done to solve my problem.
Thanks

**Comment by pfidr34** [comment]
`-e 'SYNC_SRC'='webdav-alapitvany-private:/Megosztott dokumentumok/' `

This is a config error, you have a space in your directory. 

Need to make sure that space is escaped properly.

**Comment by l4t3b0** [comment]
Dear pfidr34

Let me disaggree with your evaluation. I do believe, that this is an issue within the sync.sh.

The space is intentional in the SYNC_SRC variable.
I do believe, that because of the single quotation mark it is escaped the correct way.
`-e 'SYNC_SRC'='webdav-alapitvany-private:/Megosztott dokumentumok/'
`
To prove it i have modified locally the sync.sh.
On my side this is how it looks like:
```
# head sync.sh
#!/bin/sh

set -e

echo "INFO: Starting sync.sh pid $$ $(date)"

echo "DEBUG output to trace whitespace problems in SYNC_SRC:"$SYNC_SRC";"


# Delete logs by user request

```
With the above modification I have generated the following output:

> INFO: Running rclone v1.51.0
> INFO: Cron shortcut @weekly re-written to 0 0 * * 0
> INFO: Starting sync.sh pid 30 Tue May 12 08:57:02 CEST 2020
> DEBUG output to trace whitespace problems in SYNC_SRC:webdav-alapitvany-private:/Megosztott dokumentumok/;
> INFO: Removing logs older than 120 day(s)...

So it tells me, that the sync.sh scripts gets the environment variable the proper way.

I believe the problem is how the SYNC_SRC environment variable is handled within the script.
For example at line 57 instead of
`if test "$(rclone $RCLONE_DIR_CMD $SYNC_SRC $RCLONE_OPTS)"; then`
it should be like:
`if test "$(rclone $RCLONE_DIR_CMD "$SYNC_SRC" $RCLONE_OPTS)"; then`

What is your opinion?

**Comment by pfidr34** [comment]
Will take a look this weekend.

**Comment by pfidr34** [comment]
@l4t3b0, thanks for submitting this issue. 

I was able to replicate and fix this as well as catching white spaces in `SYNC_DEST`.

Checked in to GitHub with commit [2df3451](https://github.com/pfidr34/docker-rclone/commit/2df34519779045aa7325158764736e46a4e71f7b)

Also posted a new build to Docker Hub.

Have a great weekend!
