### ISSUE TITLE
Improvement: optimize rclone ls run

### ISSUE THREAD

**Issue by l4t3b0** [pfidr34/docker-rclone#17]
Hi pfidr34

I have a huge amount of data in the cloud that i would  like to sync. (over 300GB data, over 36000 files and 500 directories).

Running the rclone ls can take a lot of time because it is recursive.

Im not quite sure what the purpose is to run the rclone ls before the sync, but based on the sync.sh it is something to make sure that the source directory is not empty - that might cause data loss.

If the reason to make sure that the source directory is not empty, than it should not ls the directories recursively.

Please consider to use “--max-depth 1” to stop the recursion.

**Comment by pfidr34** [comment]
I have added a new parameter called `RCLONE_DIR_CMD_DEPTH` where you can specify depth.
