### ISSUE TITLE
Improvement: healthcheck start should be triggered before rclone ls

### ISSUE THREAD

**Issue by l4t3b0** [pfidr34/docker-rclone#18]
Hi pfidr34

I have a huge amount of data in the cloud that i would like to sync. (over 300GB data, over 36000 files and 500 directories).

Running the rclone ls can take a lot of time because it is recursive.

From the user perspective it is very strange that the sync.sh is already running but i see no sight of that at the https://healthchecks.io/ webpage.
This is because the start url is triggered only after the rclone ls.

It is also missleading because of the total elapsed execution time of the script.

Please consider to trigger the start url of the healthchecks.io before starting the ls command.

**Comment by pfidr34** [comment]
I have changed where the start signal for healthchecks.io occurs.
