### ISSUE TITLE
Improvement: deleting older logs only if the sync.sh starts

### ISSUE THREAD

**Issue by l4t3b0** [pfidr34/docker-rclone#19]
Hi pfidr34

Currently the sync.sh script is deleting older logs and after that it checks for other instances of running rclone processes.
We might delete actual running process's log now and than quit because of the other process. Therefore loosing necessary logs.

Please consider to execute these two steps in the reverse order.

**Comment by pfidr34** [comment]
Agree.

**Comment by pfidr34** [comment]
I have changed where the log deletion occurs to prevent the scenario you described.
