### ISSUE TITLE
Error when executing move command with RCLONE_DIR_CHECK_SKIP 

### ISSUE THREAD

**Issue by dantebarba** [pfidr34/docker-rclone#22]
Hey!. Looks like something is not working right with the skip check command: I have to activate it because I sometimes need to execute a move command when a directory is empty, and healthcheck in that case should be successful. So the option was to deactivate the source check. Anyway, the same configuration without SKIP works, but when I add the SKIP environment it fails with the following message:

```
INFO: Skipping source directory check...
INFO: Starting rclone move MyServer:/root/docker/sonarr/tvseries /destination --config /config/rclone.conf -v --min-age 30d --delete-empty-src-dirs
2020/06/11 16:40:58 ERROR : : error reading source directory: directory not found

```

But when I deactivate SKIP SOURCE CHECK:

```
INFO: Source directory is not empty and can be processed without clear loss of data
INFO: Starting rclone move MyServer:/root/docker/sonarr/tvseries /destination --config /config/rclone.conf -v --min-age 30d --delete-empty-src-dirs
2020/06/11 16:55:01 INFO  : Waco/Season 1/Waco (2018) - S01E01 - : Copied (new)
```

**Comment by dantebarba** [comment]
This is driving me nuts. I'm testing the same command that is printed on the log inside the container using -it /bin/sh and it works:

`2020/06/18 21:43:09 INFO  : There was nothing to transfer
2020/06/18 21:43:09 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Elapsed time:         0.0s`

But when executing` ./sync.sh`

`2020/06/18 21:42:41 ERROR : : error reading source directory: directory not found
2020/06/18 21:42:41 INFO  : There was nothing to transfer
2020/06/18 21:42:41 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2020/06/18 21:42:41 ERROR : : error reading source directory: directory not found
2020/06/18 21:42:41 INFO  : There was nothing to transfer
2020/06/18 21:42:41 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2020/06/18 21:42:41 ERROR : : error reading source directory: directory not found
2020/06/18 21:42:41 INFO  : There was nothing to transfer
2020/06/18 21:42:41 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
2020/06/18 21:42:41 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         0.0s`

@pfidr34 any ideas?

**Comment by dantebarba** [comment]
hey @pfidr34 I've found the issue. There is a missing "$" inside the eval command. It looks like the bugfix hasn't been pushed to docker hub. Please can you push the latest version with the fix?.

<img width="1012" alt="Screen Shot 2020-06-18 at 21 55 52" src="https://user-images.githubusercontent.com/6656541/85085527-8579cf80-b1ae-11ea-9a43-8aa8c1b388ea.png">

As you can see on the 14th line there is a missing "$" for SYNC_SRC.

**Comment by pfidr34** [comment]
@dantebarba wow, you are so right. Sorry about that.

Will rebuild and push now.

**Comment by pfidr34** [comment]
@dantebarba new builds are on DockerHub.

Let me know if this is resolved for you.

**Comment by dantebarba** [comment]
No worries we appreciate the effort you are putting into it. 

It's working perfectly now thanks!.

**Comment by pfidr34** [comment]
@dantebarba glad to hear its working for you now.

Appreciate the thanks.
