### ISSUE TITLE
TASK_TIMEOUT instead of CRON_ABORT

### ISSUE THREAD

**Issue by dantebarba** [pfidr34/docker-rclone#27]
Hey,

For some cases CRON_ABORT is not useful enough. e.g I usually upload data from different nodes to gdrive. The task is scheduled to run every minute. Unfortunately I don't have a way to stop rclone if it's taking too long to finish. 
Because of this use case, an option could be added to specify a timer that controls the cron job, and kills it after the desired timelapse is met. Could be something like:

`TASK_TIMEOUT: 1m|1h|30s|30m ...
` 

Is it doable? Thanks

**Comment by pfidr34** [comment]
@dantebarba 

Just wanted to give you an update that I have read this issue and I think it is a good idea. 

I am currently very busy at work and have not had time to look into this but may in the future. 

If you would like to submit a pull request for this feature I would also be happy to review that.

**Comment by dantebarba** [comment]
Closing because this can be done by using the `--max-duration` flag

https://forum.rclone.org/t/how-to-stop-rclone-move-after-time/40977
