### ISSUE TITLE
Critical bug: Healtcheck is reporting ok but rclone failed in case DIR_CHECK, no OUTPUT_LOG

### ISSUE THREAD

**Issue by mistermult** [pfidr34/docker-rclone#30]
# Problem
When running the container with DIR_CHECK but no OUTPUT_LOG, the return code of rclone is always picket up as 0. As a result, the healtcheck always reports everything is ok despite the sync/backup failing. 

# Reason
In the code, the return code `RETURN_CODE` of `set` is picked up instead of `eval "rclone ..."`. 
```bash
set +e
eval "rclone $RCLONE_CMD $SYNC_SRC $SYNC_DEST $RCLONE_OPTS $SYNC_OPTS_ALL"
set -e
export RETURN_CODE=$?
```

# Solution
Change the order of `set -e` and `export RETURN_CODE=$?`. See my PR #29.

**Comment by pfidr34** [comment]
Merged.
