### ISSUE TITLE
Beta build for rclone

### ISSUE THREAD

**Issue by G4brym** [pfidr34/docker-rclone#32]
Hi, is it possible for us to also have a docker build for the latest rclone beta?

I'm trying to use the new Cloudflare R2 storage, and that is currently only available in the rclone v1.59.0 beta

Check the forum thread [here](https://forum.rclone.org/t/cloudflare-r2-now-working-with-rclone/30730)

**Comment by pfidr34** [comment]
@G4brym unfortunately I do not compile and publish beta builds. When the feature makes it to a public release it will make its was into my repo.

You can try to check out the official rClone repo on docker hub, as they publish their betas there. Best of luck!

[https://hub.docker.com/r/rclone/rclone/tags](https://hub.docker.com/r/rclone/rclone/tags)
