### ISSUE TITLE
Allow multiple commands in same execution

### ISSUE THREAD

**Issue by germancasares** [pfidr34/docker-rclone#37]
Hi!

First of all, thank you for maintaining the fork!

I have a use case where I want to do something like:

A:/some/folder to B:/some/folder
B:/another/folder to C:/some/different/name
B:/foo/folder to C:/bar/
B:/foo/random to C:/john/
etc...

Like running multiple copy/sync commands. How could I pass an array of SRC/DEST instead of just 1 combination?

**Comment by dantebarba** [comment]
I had this issue before. I ended up just scheduling multiple instances with different configuration.

**Comment by pfidr34** [comment]
@germancasares this is a good suggestion and exactly how I manage my setup as well.

While I know this was not the nature of your request, I would consider this a viable solution and am going to close this issue.

Thanks for logging this.
