### ISSUE TITLE
image: pfidr/rclone:latest still shows rclone 1.58  

### ISSUE THREAD

**Issue by perler** [pfidr34/docker-rclone#38]
when running "rclone --version" in a docker container run with

`image: pfidr/rclone:latest
`
still shows 1.58.

here a screenshot from portainer:
![image](https://user-images.githubusercontent.com/623092/207398319-e165da32-82ee-4d74-a220-8340db8af701.png)

**Comment by pfidr34** [comment]
This has been updated.

**Comment by perler** [comment]
just to clarify, the rclone version has been updated or was this a bug?

**Comment by pfidr34** [comment]
rclone version has been updated. 

My URL watcher to alert me about new versions of rclone was not working.
