### ISSUE TITLE
Update rclone to v1.63.0

### ISSUE THREAD

**Issue by cfunseth** [pfidr34/docker-rclone#39]
First off, love the image and wanted to thank you for creating and maintaining it!

I noticed that this image is a couple versions behind the current release listed on rclone's website. Any chance of having your image updated to the latest version? (v1.63.0 as of the time of me writing this)

I could take a stab at creating a PR if you don't have the time, I just wanted to check in with you first.

Thank you!

**Comment by pfidr34** [comment]
@cfunseth thanks for logging this issue. My service that alerts me to new releases is not firing 👎, I'll take a look.

In the mean time, I have manually pushed version 1.63.0 for you. 

Appreciate the support, have a great day!
