### ISSUE TITLE
Eval arguments to support --backup-dir

### ISSUE THREAD

**Issue by mistermult** [pfidr34/docker-rclone#4]
Consider the following command that syncs files. It does not overwrite old files but moves them to a backup directory that depends on the time when rclone is executed, e.g. "dst_backup2019-09-12"
```bash
rclone sync "/src" "/dst" --backup-dir "/dst_backup"`date -I`--config /.config/conf.conf
```
To do this in the container the SYNC_OPT has to be evaluated. I suggest adding another variable SYNC_OPT_EVAL to the container, because there might be unforeseeable bugs if everything is evaluated.  Then add the following lines before rclone is called in sync.sh:

```bash
SYNC_OPT_EVALUALTED=$(eval echo $SYNC_OPT_EVAL)
SYNC_OPT_ALL="${SYNC_OPT} ${SYNC_OPT_EVALUALTED}"
### Use SYNC_OPT_ALL instead of SYNC_OPT in following rclone command
```
The we can use docker-rclone with
```
-e '--backup-dir /dst_backup`date -I`'
```
to replicate the above command.

I'm happy to create a PR with the changes and waiting for your approval.

**Comment by pfidr34** [comment]
Please send a PR, I will review and test.

**Comment by pfidr34** [comment]
Merged, tweaked and uploaded to docker hub. Thanks for the PR!

**Comment by mistermult** [comment]
Thank you!
