### ISSUE TITLE
How to cancel sync jobs

### ISSUE THREAD

**Issue by cwillhelm** [pfidr34/docker-rclone#6]
Hi, I was just curious how I would be able to cancel the sync job without modifying the bash script?

I know you can set the `CRON_ABORT` environment variable, but it just says that there is no outstanding sync, and the container continues to run.

Basically what I want to do is have rclone upload to a remote location, and then once the upload is complete, have the container exit. 

I don't mind modifying the bash script to achieve this functionality, but I was just wondering if there was an easier way so I could stay inline with the upstream repository.

**Comment by pfidr34** [comment]
@cwillhelm this is checked in and uploaded to Docker Hub.

Using SYNC_ONCE=1 will run the sync once then exit the container.

Example log:
```
INFO: Running rclone v1.49.3
INFO: Cron shortcut @weekly re-written to 0 0 * * 0
INFO: Starting sync.sh pid 33 Mon Sep 23 09:30:06 CDT 2019
INFO: Removing logs older than 7 day(s)...
INFO: Source directory is not empty and can be processed without clear loss of data
INFO: Log file output to /logs/2019_09_23-09_30_08.txt
INFO: Starting rclone copy GDrive:/1 OneD:/1 --config /config/rclone.conf --drive-acknowledge-abuse -v --exclude /C/** --log-file=/logs/2019_09_23-09_30_08.txt
INFO: Define CHECK_URL with https://healthchecks.io to monitor copy job
INFO: SYNC_ONCE option activated. Stopping now.
```

Container status:
`Stopped for 40 minutes with exit code 0`
