### ISSUE TITLE
Drop in replacement?

### ISSUE THREAD

**Issue by onedr0p** [pfidr34/docker-rclone#7]
I am currently using @bcardiff docker image, is there anything I need to change besides updating to your docker image? I read thru the new features you added but I just wanted to make sure.

Thanks for keeping an updated image.

**Comment by pfidr34** [comment]
@onedr0p yes this should be a drop in. When I forked and updated my goal was to extend functionality while leaving the core code intact for users like you that want an easy switch.

If you switch over and something is different, please let me know so I can take a look.

**Comment by onedr0p** [comment]
Awesome, I'll report back if I find any issue.
