### ISSUE TITLE
pls post any example for rclone sync with gdrive 

### ISSUE THREAD

**Issue by shrikant2002** [pfidr34/docker-rclone#8]
pls post any example for rclone sync with gdrive with cron

**Comment by pfidr34** [comment]
> do i have to add the following in task scheduler in my synology nas ??
> sudo docker run --rm -it -v $(pwd)/config:/config -e SYNC_SRC="kd6:/Test" -e SYNC_DEST="kd2:/Test" -e TZ="America/Chicago" -e CRON="0 * * ? * *" pfidr/rclone

You should only have to run that docker command once, the CRON environment variable will run the sync job as needed.

Just make sure you have a cron set up on the Synology to start the container if you reboot the NAS.

Also, not sure if CRON can take a questions mark, try changing that.

**Comment by pfidr34** [comment]
Closing for now. Let me know if you have another issue.
