### ISSUE TITLE
Running rclone as different user in the container

### ISSUE THREAD

**Issue by mikeburgh** [pfidr34/docker-rclone#9]
Any suggestions for how I could change the docker user that's running rlcone inside the container.

By default it's running as root, so the files it syncs into the mounted folder come out as root:root.

If I pass in the user to the docker run command, it errors out on accessing crontab (timezone) which makes sense

```
# docker run ... --user=90:1000
INFO: Running rclone v1.50.1
INFO: Starting sync.sh pid 30 Wed Nov 13 15:38:27 UTC 2019
WARNING: Source directory is empty. Skipping move command.

/entrypoint.sh: line 80: crontab: Permission denied
```

**Comment by pfidr34** [comment]
Noted. I will work on this, will take a little time though.
